# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0c2ec1e55c2e565b8a146ef81ab560615db4c59e3a72e2aedbebcae524cc1ce62a3fd766d8ff32eb9dd7e2f06011f3c3af62249d7e77ef7699feb2a3417cec7

test:
  secret_key_base: c0410d4d3543fad314d04801e1d4870bdac3901fcf9e40c7045af4e60a293c8b7702658f388348ced571725f4c95dae354b77752e10a5116344427ad3822019c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
